### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by zixunlu**

### CODE REVIEW

**Comment by pop** [comment]
You need to compile the documents multiple times. 10 compiles per document.

**Comment by pop** [comment]
https://svn.apache.org/repos/asf/xalan

**Comment by pop** [comment]
@zixunlu Please add a new column on the right which lists the averages.
Also turn the one table into three. One table for Altova, one for Xalan, and a third table for putting the averages side by side (but include the averages in the individual software's tables).

**Comment by zixunlu** [comment]
ok. I will change it.

**Pull request closed without merging**
